# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language: python
        types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort
        language: python
        types: [python]
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
        language: python
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language: python
        types: [python]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        language: python
        types: [python]
        args: ["-iii", "-ll"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        language: python
        types: [python]
        exclude: "tests/"
        additional_dependencies:
          - "pydantic==1.8.2"
          - "httpx==0.18.1"
          - "ward==0.59.0-beta.0"
